console.log("Hello Winc Academy");
let name = "Tomas";
console.log(name);
let som = 10 + 11;
console.log("som:", som);
let somMetStrings = "Tomas" + "Gons";
console.log("som met strings", somMetStrings);
let multiply = 3 * 5;
console.log("multiply", multiply);
let divide = 233 / 36;
console.log("divide", divide);
let subtract = 50 - 45;
console.log("subtract", subtract);
let modulus = 50 % 20;
console.log("modulus:", modulus);
let age = 43;
console.log(typeof age);
let ageAsString = "43";
console.log(typeof ageAsString);
